### ISSUE TITLE
Adding an overflowed CM/CSM a CSS padding (> 0) leads to incorrect CM/CSM height determination

### ISSUE THREAD

**Issue by smellyshovel** [smellyshovel/custom-context-menu#6]
If a CM/CSM has a padding CSS property, for example:

```CSS
[data-cm] {
    padding: 1rem;
}
```

And if the CM/CSM is overflowed, then it won't fit the bottom edge of the viewport.
